spring:
  application:
    name: "TicketPurchaseService"
  devtools:
    add-properties: false
  profiles:
    active: ${ENV:local}
aws:
  region: ${AWS_REGION:us-east-1}
adapter:
  dynamodb:
    tickets-table-name: ${TICKETS_TABLE_NAME:tickets}
    orders-table-name: ${ORDERS_TABLE_NAME:orders}
entrypoint:
  sqs:
    region: ${AWS_REGION:us-east-1}
    queueUrl: ${PURCHASE_QUEUE_URL:http://localstack:4566/000000000000/purchase-requests}
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
---
spring:
  config:
    activate:
      on-profile: local
aws:
  dynamodb:
    endpoint: ${AWS_DYNAMODB_ENDPOINT:http://dynamodb-local:8000}
entrypoint:
  sqs:
    endpoint: ${AWS_SQS_ENDPOINT:http://localstack:4566}
